### ISSUE TITLE
Use slimier base to create slimier image

### ISSUE THREAD

**Issue by shirani182** [christopher-talke/node-express-puppeteer-pdf-example#1]
Image size is ~2G.
I tried using node:alpine as you suggested and it's not working.
so you know which image does work

**Comment by christopher-talke** [comment]
`node:alpine` requires additional configuration within the dockerfile, I havn't found a need to lower the image size for awhile now, and in turn I havn't had the time to create a guide for Alpine image yet, nor do I think I'll find time soon.

If I can, I'll go ahead and commit some code to get node:alpine working... no promises..

In the meantime, give this repo a shot, another one of my friends has used this blokes image in a few deployments where a small image size was a requirement: [Click Here](https://github.com/Zenika/alpine-chrome)
